const dictionary = {
  "es": {
    "Inici": "Inicio",
    "Història": "Historia",
    "Personatges i Objectes": "Personajes y Objetos",
    "Objectius": "Objetivos",
    "Ranking": "Ranking",
    "Comentaris": "Comentarios",
    "Xarxes socials del joc:": "Redes sociales del juego:",
    "Xarxes socials dels creadors:": "Redes sociales de los creadores:",
    "© 2026 Escamas de Cautiverio. Tots els drets reservats.": "© 2026 Escamas de Cautiverio. Todos los derechos reservados.",
    "© 2026 Escamas de Cautiverio. Todos los derechos reservados.": "© 2026 Escamas de Cautiverio. Todos los derechos reservados.",
    "BENVINGUT A OUT": "BIENVENIDO A OUT",
    "De què tracta OUT?": "¿De qué trata OUT?",
    "OUT: Escamas de Cautiverio és una novel·la visual que narra la trobada entre un protagonista solitari i un ésser aquàtic captiu. A través d'una atmosfera malenconiosa, el joc explora la connexió emocional que neix entre dos \"presoners\" —un físic i l'altre emocional— i com les decisions del jugador determinen si aquesta relació portarà a la llibertat o a la perdició.": "OUT: Escamas de Cautiverio es una novela visual que narra el encuentro entre un protagonista solitario y un ser acuático cautivo. A través de una atmósfera melancólica, el juego explora la conexión emocional que nace entre dos \"prisioneros\" —uno físico y el otro emocional— y cómo las decisiones del jugador determinan si esta relación llevará a la libertad o a la perdición.",
    "Personatges": "Personajes",
    "El Protagonista: L'Erudit de l'Exili": "El Protagonista: El Erudito del Exilio",
    "No ets un guerrer de primera línia, però posseseixes una agilitat i un intel·lecte superiors. Com a expert en botànica i alquímia, la teva força resideix en la teva capacitat per llegir l'entorn. La teva armadura d'explorador està dissenyada per al sigil, i el teu coneixement de les Runes de Poder és l'única clau que pot obrir-te les portes cap a la llibertat.": "No eres un guerrero de primera línea, pero posees una agilidad y un intelecto superiores. Como experto en botánica y alquimia, tu fuerza reside en tu capacidad para leer el entorno. Tu armadura de explorador está diseñada para el sigilo, y tu conocimiento de las Runas de Poder es la única clave que puede abrirte las puertas hacia la libertad.",
    "Els Antagonistes: La Legió del Queixal Trencat": "Los Antagonistas: La Legión del Colmillo Roto",
    "Els Carcellers: Bruts implacables que patrullen els passadissos. El seu olfacte és agut, però la seva intel·ligència és limitada.": "Los Carceleros: Brutos implacables que patrullan los pasillos. Su olfato es agudo, pero su inteligencia es limitada.",
    "El Gran Estrateg Orc: El cervell darrere de la imminent invasió. És qui ha ordenat el teu interrogatori.": "El Gran Estratega Orco: El cerebro detrás de la inminente invasión. Es quien ha ordenado tu interrogatorio.",
    "Les Bèsties de Caça: Criatures de la fauna local que els orcs han domesticat per custodiar les zones més fosques de la presó.": "Las Bestias de Caza: Criaturas de la fauna local que los orcos han domesticado para custodiar las zonas más oscuras de la prisión.",
    "Descobreix-los": "Descúbrelos",
    "El teu camí cap a la redempció i la salvació de la teva raça es divideix en tres pilars fonamentals:": "Tu camino hacia la redención y la salvación de tu raza se divide en tres pilares fundamentales:",
    "Infiltració i Supervivència: Mou-te entre les ombres. Evita la confrontació directa sempre que sigui possible, ja que et superen en nombre. Esquiva trampes mortals dissenyades per aturar qualsevol intrús.": "Infiltración y Supervivencia: Muévete entre las sombras. Evita la confrontación directa siempre que sea posible, ya que te superan en número. Esquiva trampas mortales diseñadas para detener a cualquier intruso.",
    "Espionatge Tàctic: Al llarg dels nivells, trobaràs documents i mapes de guerra. Recollir aquesta informació és vital per advertir el teu Rei sobre els moviments militars dels Orcs.": "Espionaje Táctico: A lo largo de los niveles, encontrarás documentos y mapas de guerra. Recopilar esta información es vital para advertir a tu Rey sobre los movimientos militares de los Orcos.",
    "El Ritual de les Runes: Per obrir la Gran Porta que connecta els erms amb el teu regne, hauràs de localitzar i col·locar les Runes Ancestrals en els pedestals correctes. Només així canalitzaràs la màgia necessària per guanyar la partida i segellar la teva escapada.": "El Ritual de las Runas: Para abrir la Gran Puerta que conecta los páramos con tu reino, deberás localizar y colocar las Runas Ancestrales en los pedestales correctos. Solo así canalizarás la magia necesaria para ganar la partida y sellar tu escape.",
    "Llegeix-los": "Léelos",
    "Invocant l'elit del Top 3...": "Invocando a la élite del Top 3...",
    "🏆": "🏆",
    "Ets el millor?": "¿Eres el mejor?",
    "La supervivència és només el primer pas; el mestratge és el que et defineix.": "La supervivencia es solo el primer paso; la maestría es lo que te define.",
    "A la nostra secció de Classificacions Mundials, podràs mesurar el teu rendiment contra altres exploradors d'arreu del món.": "En nuestra sección de Clasificaciones Mundiales, podrás medir tu rendimiento contra otros exploradores de todo el mundo.",
    "Velocitat d'Escapada: Quina rapidesa tens per sortir de les masmorres? Cada segon compta.": "Velocidad de Escape: ¿Qué tan rápido puedes salir de las mazmorras? Cada segundo cuenta.",
    "Informació Recollida: Només els més observadors trobaran tots els secrets dels orcs per obtenir la puntuació màxima.": "Información Recopilada: Solo los más observadores encontrarán todos los secretos de los orcos para obtener la puntuación máxima.",
    "Mode Sigil: Bonificacions especials per a aquells que aconsegueixin completar nivells sense ser detectats ni una sola vegada.": "Modo Sigilo: Bonificaciones especiales para aquellos que logren completar niveles sin ser detectados ni una sola vez.",
    "\"El coneixement és la poció més forta, i la llibertat és l'ingredient més rar.\"": "\"El conocimiento es la poción más fuerte, y la libertad es el ingrediente más raro.\"",
    "— Màxima de l'explorador Draconià.": "— Máxima del explorador Draconiano.",
    "Veure Rànquing complet": "Ver Ranking completo",
    "📜": "📜",
    "Uneix-te a": "Únete a",
    "la foscor": "la oscuridad",
    "Tens alguna pregunta, suggerència o simplement vols donar la teva opinió?": "¿Tienes alguna pregunta, sugerencia o simplemente quieres dar tu opinión?",
    "El nostre grup d'Erudits sempre està obert a noves veus per intercanviar coneixements, reportar errors a les masmorres o suggerir camins inexplorats.": "Nuestro grupo de Eruditos siempre está abierto a nuevas voces para intercambiar conocimientos, reportar errores en las mazmorras o sugerir caminos inexplorados.",
    "Només si entres en contacte amb el nostre clan podràs entendre els misteris que envolten la teva arribada.": "Solo si entras en contacto con nuestro clan podrás entender los misterios que envuelven tu llegada.",
    "Contacta'ns": "Contáctanos",
    "✉️": "✉️",
    "LA LLEGENDA": "LA LEYENDA",
    "\"En la foscor més profunda, les escates brillen amb el passat que no pot ser oblidat.\"": "\"En la oscuridad más profunda, las escamas brillan con el pasado que no puede ser olvidado.\"",
    "L'Origen del Captiveri": "El Origen del Cautiverio",
    "En un món fracturat per la desconfiança, els Draconians i els Orcs han mantingut una treva armada que penja d'un fil. Durant dècades, el Regne dels Cims (Draconians) ha prioritzat el coneixement i la sanació, mentre que les Tribus dels Erms (Orcs) han enfortit la seva maquinària de guerra. Tu encarnes un Mestre Explorador de l'Ordre Alquímica. La teva missió era noble i senzilla: endinsar-te en els perillosos Monts de Cendra per recolectar la \"Arrel de Sang\", l'únic ingredient capaç d'aturar una plaga que assola els cadells de la teva raça. Malauradament, la fortuna no va estar del teu costat. Una patrulla d'orcs, cegada per l'odi ancestral i la paranoia, et va emboscar als passos fronterers.": "En un mundo fracturado por la desconfianza, los Draconianos y los Orcos han mantenido una tregua armada que pende de un hilo. Durante décadas, el Reino de las Cumbres (Draconianos) ha priorizado el conocimiento y la sanación, mientras que las Tribus de los Páramos (Orcos) han fortalecido su maquinaria de guerra. Tú encarnas a un Maestro Explorador de la Orden Alquímica. Tu misión era noble y sencilla: adentrarte en los peligrosos Montes de Ceniza para recolectar la \"Raíz de Sangre\", el único ingrediente capaz de detener una plaga que asola a los cachorros de tu raza. Desgraciadamente, la fortuna no estuvo de tu lado. Una patrulla orca, cegada por el odio ancestral y la paranoia, te emboscó en los pasos fronterizos.",
    "L'Arribada del Solitari": "La Llegada del Solitario",
    "Confós amb un espia d'elit a causa dels teus mapes i coneixements del terreny, has estat llançat a les Masmorres de Ferro Negre. Però els orcs han comès un error: no saben que un Draconià és més perillós quan no té res a perdre.": "Confundido con un espía de élite debido a tus mapas y conocimientos del terreno, has sido arrojado a las Mazmorras de Hierro Negro. Pero los orcos han cometido un error: no saben que un Draconiano es más peligroso cuando no tiene nada que perder.",
    "Les Veus de l'Abisme": "Las Voces del Abismo",
    "Ara, mentre els tambors de guerra ressonen en les profunditats, hauràs d'utilitzar la teva astúcia per escapar, descobrir els seus plans d'invasió i utilitzar les runes ancestrals per segellar el seu destí abans que sigui massa tard per al teu Rei i el teu poble.": "Ahora, mientras los tambores de guerra resuenan en las profundidades, deberás utilizar tu astucia para escapar, descubrir sus planes de invasión y utilizar las runas ancestrales para sellar su destino antes de que sea demasiado tarde para tu Rey y tu pueblo.",
    "Un Camí sense Retorn": "Un Camino sin Retorno",
    "En \"Escamas de Cautiverio\", la història no s'escriu amb tinta, sinó amb voluntat.": "En \"Escamas de Cautiverio\", la historia no se escribe con tinta, sino con voluntad.",
    "Cada interacció és un fil en un teixit complex. Qui és realment el monstre? Aquell que està darrere de les reixes, o aquell que té la clau a la mà?": "Cada interacción es un hilo en un tejido complejo. ¿Quién es realmente el monstruo? ¿Aquél que está detrás de las rejas, o aquél que tiene la llave en la mano?",
    "Descobreix més": "Descubre más",
    "Ets un draconiani capturat pels orcs mentre exploraves els seus erms i muntanyes. No ets un soldat ni un espia: només un explorador dedicat a estudiar la fauna i la flora del món per ajudar en la creació de pocions i remeis que curin els malalts del teu regne. Però els orcs, marcats per una antiga rivalitat amb la teva raça, et confonen amb un infiltrat. La desconfiança i l’odi acumulat entre ambdues espècies ja va provocar una guerra, i qualsevol trobada és vista com una amenaça.": "Eres un draconiano capturado por los orcos mientras explorabas sus páramos y montañas. No eres un soldado ni un espía: solo un explorador dedicado a estudiar la fauna y la flora del mundo para ayudar en la creación de pociones y remedios que curen a los enfermos de tu reino. Pero los orcos, marcados por una antigua rivalidad con tu raza, te confunden con un infiltrado. La desconfianza y el odio acumulado entre ambas especies ya provocaron una guerra, y cualquier encuentro es visto como una amenaza.",
    "Enemic": "Enemigo",
    "Aquest guerrer és un Vigilant de Frontera, encarregat de patrullar els límits del territori orc i capturar qualsevol intrús que s’hi atreveixi a entrar. Armat amb una destral massissa i cobert amb una armadura forjada a mà, és conegut per la seva força bruta i la seva lleialtat absoluta al clan. Per als orcs, qualsevol draconiani que trepitgi les seves terres és un espia, i aquest Vigilant no dubta a actuar abans de preguntar.": "Este guerrero es un Vigilante de Frontera, encargado de patrullar los límites del territorio orco y capturar a cualquier intruso que se atreva a entrar. Armado con un hacha maciza y cubierto con una armadura forjada a mano, es conocido por su fuerza bruta y su lealtad absoluta al clan. Para los orcos, cualquier draconiano que pise sus tierras es un espía, y este Vigilante no duda en actuar antes de preguntar.",
    "Aquest guerrer és un Vigilant de Frontera, encarregat de patrullar els límits del territorori orc i capturar qualsevol intrús que s’hi atreveixi a entrar. Armat amb una destral massissa i cobert amb una armadura forjada a mà, és conegut per la seva força bruta i la seva lleialtat absoluta al clan. Per als orcs, qualsevol draconiani que trepitgi les seves terres és un espia, i aquest Vigilant no dubta a actuar abans de preguntar.": "Este guerrero es un Vigilante de Frontera, encargado de patrullar los límites del territorio orco y capturar a cualquier intruso que se atreva a entrar. Armado con un hacha maciza y cubierto con una armadura forjada a mano, es conocido por su fuerza bruta y su lealtad absoluta al clan. Para los orcos, cualquier draconiano que pise sus tierras es un espía, y este Vigilante no duda en actuar antes de preguntar.",
    "Enemic del tutorial": "Enemigo del tutorial",
    "Un antic guerrer orc que va ser sotmès a rituals prohibits per convertir-lo en una arma viventa. La corrupció li ha consumit la ment, però li ha multiplicat la força. Ara només respon a instints primaris: atacar, destruir i protegir la fortalesa subterrània. Els seus ulls vermells brillen amb una fúria incontrolable, i les seves armes, decorades amb cranis, són un recordatori del seu passat com a botxí del clan. Tot i la seva aparença aterridora, és el primer enemic ideal per aprendre les mecàniques bàsiques": "Un antiguo guerrero orco que fue sometido a rituales prohibidos para convertirlo en un arma viviente. La corrupción ha consumido su mente, pero ha multiplicado su fuerza. Ahora solo responde a instintos primarios: atacar, destruir y proteger la fortaleza subterránea. Sus ojos rojos brillan con una furia incontrolable, y sus armas, decoradas con cráneos, son un recordatorio de su pasado como verdugo del clan. A pesar de su apariencia aterradora, es el primer enemigo ideal para aprender las mecánicas básicas.",
    "Trampes": "Trampas",
    "Les ruïnes orques estan protegides per antics mecanismes dissenyats per eliminar intrusos. Algunes plataformes activen espines metàl·liques quan detecten pes, mentre que altres reaccionen a la proximitat, elevant punxes des d’un nucli vermell carregat d’energia arcana. Són trampes ràpides, letals i imprevisibles, creades per mantenir fora qualsevol que s’atreveixi a desafiar el domini del clan. Si vols, puc fer una versió encara més breu per a una targeta, o una més èpica per donar més ambient.": "Las ruinas orcas están protegidas por antiguos mecanismos diseñados para eliminar intrusos. Algunas plataformas activan espinas metálicas cuando detectan peso, mientras que otras reaccionan a la proximidad, elevando pinchos desde un núcleo rojo cargado de energía arcana. Son trampas rápidas, letales e imprevisibles, creadas para mantener fuera a cualquiera que se atreva a desafiar el dominio del clan. Si quieres, puedo hacer una versión aún más breve para una tarjeta, o una más épica para dar más ambiente.",
    "MISSIONS PRINCIPALS": "MISIONES PRINCIPALES",
    "\"La teva supervivència depèn de la teva capacitat per adaptar-te i superar els reptes de l'abisme.\"": "\"Tu supervivencia depende de tu capacidad para adaptarte y superar los retos del abismo.\"",
    "01": "01",
    "Escapa de les trampes!": "¡Escapa de las trampas!",
    "L'entorn és el teu primer enemic. Hi ha diversos puzzles i trampes repartides arreu de la masmorra. Sigues cautelós, observa els patrons i utilitza la teva agudesa mental per no caure-hi.": "El entorno es tu primer enemigo. Hay varios puzzles y trampas repartidas por toda la mazmorra. Sé cauteloso, observa los patrones y utiliza tu agudeza mental para no caer en ellas.",
    "02": "02",
    "Que no t'enganin!": "¡Que no te engañen!",
    "Trobaràs enemics que intentaran aturar-te a qualsevol preu. Però compte: no tot el que es mou a la foscor és hostil. Alguns éssers poden ser vitals per a la teva experiència si saps com interactuar-hi.": "Encontrarás enemigos que intentarán detenerte a cualquier precio. Pero cuidado: no todo lo que se mueve en la oscuridad es hostil. Algunos seres pueden ser vitales para tu experiencia si sabes cómo interactuar con ellos.",
    "03": "03",
    "Escapa amb vida": "Escapa con vida",
    "L'objectiu final és la llibertat. Però a quin preu? La teva integritat física i mental es veurà posada a prova en cada nivell. Només aquells que sàpiguen gestionar els seus recursos arribaran a la sortida.": "El objetivo final es la libertad. Pero ¿a qué precio? Tu integridad física y mental se verá puesta a prueba en cada nivel. Solo aquellos que sepan gestionar sus recursos llegarán a la salida.",
    "04": "04",
    "Troba informació": "Encuentra información",
    "Descobreix el perquè del teu segrest. El món de OUT amaga secrets antics sobre el conflicte entre orcs i draconians. Troba documents i relats que revelin els plans ocults dels teus captors.": "Descubre el porqué de tu secuestro. El mundo de OUT esconde secretos antiguos sobre el conflicto entre orcos y draconianos. Encuentra documentos y relatos que revelen los planes ocultos de tus captores.",
    "Encara no hi ha dades al rànquing.": "Aún no hay datos en el ranking.",
    "Saló de la Fama": "Salón de la Fama",
    "Primer lloc": "Primer lugar",
    "Segon lloc": "Segundo lugar",
    "Tercer lloc": "Tercer lugar",
    "Resta de jugadors": "Resto de jugadores",
    "Nom": "Nombre",
    "Escriu el teu nom...": "Escribe tu nombre...",
    "Gmail": "Correo electrónico",
    "escriu.el.teu@gmail.com": "escribe.tu.correo@gmail.com",
    "Comentari": "Comentario",
    "Escriu el teu comentari...": "Escribe tu comentario...",
    "Enviar comentari": "Enviar comentario",
    "Comentaris enviats": "Comentarios enviados",
    "Encara no hi ha comentaris.": "Aún no hay comentarios."
  },
  "en": {
    "Inici": "Home",
    "Història": "History",
    "Personatges i Objectes": "Characters & Items",
    "Objectius": "Objectives",
    "Ranking": "Ranking",
    "Comentaris": "Comments",
    "Xarxes socials del joc:": "Game's social media:",
    "Xarxes socials dels creadors:": "Creators' social media:",
    "© 2026 Escamas de Cautiverio. Tots els drets reservats.": "© 2026 Escamas de Cautiverio. All rights reserved.",
    "© 2026 Escamas de Cautiverio. Todos los derechos reservados.": "© 2026 Escamas de Cautiverio. All rights reserved.",
    "BENVINGUT A OUT": "WELCOME TO OUT",
    "De què tracta OUT?": "What is OUT about?",
    "OUT: Escamas de Cautiverio és una novel·la visual que narra la trobada entre un protagonista solitari i un ésser aquàtic captiu. A través d'una atmosfera malenconiosa, el joc explora la connexió emocional que neix entre dos \"presoners\" —un físic i l'altre emocional— i com les decisions del jugador determinen si aquesta relació portarà a la llibertat o a la perdició.": "OUT: Scales of Captivity is a visual novel that tells the story of an encounter between a solitary protagonist and a captive aquatic being. Through a melancholic atmosphere, the game explores the emotional connection that is born between two \"prisoners\" - one physical and the other emotional - and how the player's decisions determine whether this relationship will lead to freedom or ruin.",
    "Personatges": "Characters",
    "El Protagonista: L'Erudit de l'Exili": "The Protagonist: The Scholar in Exile",
    "No ets un guerrer de primera línia, però posseseixes una agilitat i un intel·lecte superiors. Com a expert en botànica i alquímia, la teva força resideix en la teva capacitat per llegir l'entorn. La teva armadura d'explorador està dissenyada per al sigil, i el teu coneixement de les Runes de Poder és l'única clau que pot obrir-te les portes cap a la llibertat.": "You are not a front-line warrior, but you possess superior agility and intellect. As an expert in botany and alchemy, your strength lies in your ability to read the environment. Your explorer armor is designed for stealth, and your knowledge of the Runes of Power is the only key that can open the doors to freedom for you.",
    "Els Antagonistes: La Legió del Queixal Trencat": "The Antagonists: The Broken Fang Legion",
    "Els Carcellers: Bruts implacables que patrullen els passadissos. El seu olfacte és agut, però la seva intel·ligència és limitada.": "The Jailers: Relentless brutes who patrol the corridors. Their sense of smell is keen, but their intelligence is limited.",
    "El Gran Estrateg Orc: El cervell darrere de la imminent invasió. És qui ha ordenat el teu interrogatori.": "The Great Orc Strategist: The mastermind behind the impending invasion. He is the one who ordered your interrogation.",
    "Les Bèsties de Caça: Criatures de la fauna local que els orcs han domesticat per custodiar les zones més fosques de la presó.": "The Hunting Beasts: Creatures of the local fauna that the orcs have domesticated to guard the darkest areas of the prison.",
    "Descobreix-los": "Discover them",
    "El teu camí cap a la redempció i la salvació de la teva raça es divideix en tres pilars fonamentals:": "Your path to redemption and the salvation of your race is divided into three fundamental pillars:",
    "Infiltració i Supervivència: Mou-te entre les ombres. Evita la confrontació directa sempre que sigui possible, ja que et superen en nombre. Esquiva trampes mortals dissenyades per aturar qualsevol intrús.": "Infiltration & Survival: Move through the shadows. Avoid direct confrontation whenever possible, as they outnumber you. Dodge deadly traps designed to stop any intruder.",
    "Espionatge Tàctic: Al llarg dels nivells, trobaràs documents i mapes de guerra. Recollir aquesta informació és vital per advertir el teu Rei sobre els moviments militars dels Orcs.": "Tactical Espionage: Throughout the levels, you will find war documents and maps. Gathering this information is vital to warn your King about the Orcs' military movements.",
    "El Ritual de les Runes: Per obrir la Gran Porta que connecta els erms amb el teu regne, hauràs de localitzar i col·locar les Runes Ancestrals en els pedestals correctes. Només així canalitzaràs la màgia necessària per guanyar la partida i segellar la teva escapada.": "The Ritual of Runes: To open the Great Gate that connects the wastelands to your kingdom, you will have to locate and place the Ancestral Runes on the correct pedestals. Only then will you channel the magic needed to win the game and seal your escape.",
    "Llegeix-los": "Read them",
    "Invocant l'elit del Top 3...": "Summoning the Top 3 elite...",
    "🏆": "🏆",
    "Ets el millor?": "Are you the best?",
    "La supervivència és només el primer pas; el mestratge és el que et defineix.": "Survival is only the first step; mastery is what defines you.",
    "A la nostra secció de Classificacions Mundials, podràs mesurar el teu rendiment contra altres exploradors d'arreu del món.": "In our Global Rankings section, you can measure your performance against other explorers from around the world.",
    "Velocitat d'Escapada: Quina rapidesa tens per sortir de les masmorres? Cada segon compta.": "Escape Speed: How fast can you get out of the dungeons? Every second counts.",
    "Informació Recollida: Només els més observadors trobaran tots els secrets dels orcs per obtenir la puntuació màxima.": "Gathered Intelligence: Only the most observant will find all the orcs' secrets to get the maximum score.",
    "Mode Sigil: Bonificacions especials per a aquells que aconsegueixin completar nivells sense ser detectats ni una sola vegada.": "Stealth Mode: Special bonuses for those who manage to complete levels without being detected even once.",
    "\"El coneixement és la poció més forta, i la llibertat és l'ingredient més rar.\"": "\"Knowledge is the strongest potion, and freedom the rarest ingredient.\"",
    "— Màxima de l'explorador Draconià.": "— Maxim of the Draconian Explorer.",
    "Veure Rànquing complet": "View full Ranking",
    "📜": "📜",
    "Uneix-te a": "Join",
    "la foscor": "the darkness",
    "Tens alguna pregunta, suggerència o simplement vols donar la teva opinió?": "Do you have any questions, suggestions, or simply want to share your opinion?",
    "El nostre grup d'Erudits sempre està obert a noves veus per intercanviar coneixements, reportar errors a les masmorres o suggerir camins inexplorats.": "Our group of Scholars is always open to new voices to exchange knowledge, report bugs in the dungeons, or suggest unexplored paths.",
    "Només si entres en contacte amb el nostre clan podràs entendre els misteris que envolten la teva arribada.": "Only by contacting our clan will you be able to understand the mysteries surrounding your arrival.",
    "Contacta'ns": "Contact us",
    "✉️": "✉️",
    "LA LLEGENDA": "THE LEGEND",
    "\"En la foscor més profunda, les escates brillen amb el passat que no pot ser oblidat.\"": "\"In the deepest darkness, the scales shine with a past that cannot be forgotten.\"",
    "L'Origen del Captiveri": "The Origin of Captivity",
    "En un món fracturat per la desconfiança, els Draconians i els Orcs han mantingut una treva armada que penja d'un fil. Durant dècades, el Regne dels Cims (Draconians) ha prioritzat el coneixement i la sanació, mentre que les Tribus dels Erms (Orcs) han enfortit la seva maquinària de guerra. Tu encarnes un Mestre Explorador de l'Ordre Alquímica. La teva missió era noble i senzilla: endinsar-te en els perillosos Monts de Cendra per recolectar la \"Arrel de Sang\", l'únic ingredient capaç d'aturar una plaga que assola els cadells de la teva raça. Malauradament, la fortuna no va estar del teu costat. Una patrulla d'orcs, cegada per l'odi ancestral i la paranoia, et va emboscar als passos fronterers.": "In a world fractured by mistrust, Draconians and Orcs have maintained an armed truce hanging by a thread. For decades, the Kingdom of the Peaks (Draconians) has prioritized knowledge and healing, while the Tribes of the Wastelands (Orcs) have strengthened their war machine. You play a Master Explorer of the Alchemical Order. Your mission was noble and simple: delve into the dangerous Ash Mountains to collect the \"Blood Root\", the only ingredient capable of stopping a plague ravaging your race's cubs. Unfortunately, fortune was not on your side. An orc patrol, blinded by ancestral hatred and paranoia, ambushed you at the border passes.",
    "L'Arribada del Solitari": "The Arrival of the Loner",
    "Confós amb un espia d'elit a causa dels teus mapes i coneixements del terreny, has estat llançat a les Masmorres de Ferro Negre. Però els orcs han comès un error: no saben que un Draconià és més perillós quan no té res a perdre.": "Mistaken for an elite spy due to your maps and knowledge of the terrain, you have been thrown into the Black Iron Dungeons. But the orcs made a mistake: they don't know that a Draconian is most dangerous when they have nothing to lose.",
    "Les Veus de l'Abisme": "The Voices of the Abyss",
    "Ara, mentre els tambors de guerra ressonen en les profunditats, hauràs d'utilitzar la teva astúcia per escapar, descobrir els seus plans d'invasió i utilitzar les runes ancestrals per segellar el seu destí abans que sigui massa tard per al teu Rei i el teu poble.": "Now, as the drums of war resonate in the depths, you must use your cunning to escape, uncover their invasion plans, and use the ancient runes to seal their fate before it's too late for your King and your people.",
    "Un Camí sense Retorn": "A Point of No Return",
    "En \"Escamas de Cautiverio\", la història no s'escriu amb tinta, sinó amb voluntat.": "In \"Scales of Captivity\", history is not written with ink, but with willpower.",
    "Cada interacció és un fil en un teixit complex. Qui és realment el monstre? Aquell que està darrere de les reixes, o aquell que té la clau a la mà?": "Every interaction is a thread in a complex weave. Who is really the monster? The one behind bars, or the one holding the key?",
    "Descobreix més": "Discover more",
    "Protagonista": "Protagonist",
    "Ets un draconiani capturat pels orcs mentre exploraves els seus erms i muntanyes. No ets un soldat ni un espia: només un explorador dedicat a estudiar la fauna i la flora del món per ajudar en la creació de pocions i remeis que curin els malalts del teu regne. Però els orcs, marcats per una antiga rivalitat amb la teva raça, et confonen amb un infiltrat. La desconfiança i l’odi acumulat entre ambdues espècies ja va provocar una guerra, i qualsevol trobada és vista com una amenaça.": "You are a draconian captured by the orcs while exploring their wastelands and mountains. You are neither a soldier nor a spy: just an explorer dedicated to studying the world's fauna and flora to help create potions and remedies to heal the sick in your kingdom. But the orcs, marked by an ancient rivalry with your race, mistake you for an infiltrator. The mistrust and hatred accumulated between the two species already provoked a war, and any encounter is seen as a threat.",
    "Enemic": "Enemy",
    "Aquest guerrer és un Vigilant de Frontera, encarregat de patrullar els límits del territori orc i capturar qualsevol intrús que s’hi atreveixi a entrar. Armat amb una destral massissa i cobert amb una armadura forjada a mà, és conegut per la seva força bruta i la seva lleialtat absoluta al clan. Per als orcs, qualsevol draconiani que trepitgi les seves terres és un espia, i aquest Vigilant no dubta a actuar abans de preguntar.": "This warrior is a Border Watcher, in charge of patrolling the edges of the orc territory and capturing any intruder bold enough to enter. Armed with a massive axe and covered in hand-forged armor, he is known for his brute strength and absolute loyalty to the clan. For the orcs, any draconian stepping on their land is a spy, and this Watcher doesn't hesitate to act before asking questions.",
    "Aquest guerrer és un Vigilant de Frontera, encarregat de patrullar els límits del territorori orc i capturar qualsevol intrús que s’hi atreveixi a entrar. Armat amb una destral massissa i cobert amb una armadura forjada a mà, és conegut per la seva força bruta i la seva lleialtat absoluta al clan. Per als orcs, qualsevol draconiani que trepitgi les seves terres és un espia, i aquest Vigilant no dubta a actuar abans de preguntar.": "This warrior is a Border Watcher, in charge of patrolling the edges of the orc territory and capturing any intruder bold enough to enter. Armed with a massive axe and covered in hand-forged armor, he is known for his brute strength and absolute loyalty to the clan. For the orcs, any draconian stepping on their land is a spy, and this Watcher doesn't hesitate to act before asking questions.",
    "Enemic del tutorial": "Tutorial Enemy",
    "Un antic guerrer orc que va ser sotmès a rituals prohibits per convertir-lo en una arma viventa. La corrupció li ha consumit la ment, però li ha multiplicat la força. Ara només respon a instints primaris: atacar, destruir i protegir la fortalesa subterrània. Els seus ulls vermells brillen amb una fúria incontrolable, i les seves armes, decorades amb cranis, són un recordatori del seu passat com a botxí del clan. Tot i la seva aparença aterridora, és el primer enemic ideal per aprendre les mecàniques bàsiques": "An ancient orc warrior who was subjected to forbidden rituals to turn him into a living weapon. Corruption has consumed his mind, but multiplied his strength. He now only responds to primal instincts: attack, destroy, and protect the underground fortress. His red eyes glow with uncontrollable fury, and his skull-decorated weapons serve as a reminder of his past as the clan's executioner. Despite his terrifying appearance, he is the ideal first enemy to learn the basic mechanics.",
    "Trampes": "Traps",
    "Les ruïnes orques estan protegides per antics mecanismes dissenyats per eliminar intrusos. Algunes plataformes activen espines metàl·liques quan detecten pes, mentre que altres reaccionen a la proximitat, elevant punxes des d’un nucli vermell carregat d’energia arcana. Són trampes ràpides, letals i imprevisibles, creades per mantenir fora qualsevol que s’atreveixi a desafiar el domini del clan. Si vols, puc fer una versió encara més breu per a una targeta, o una més èpica per donar més ambient.": "The orcish ruins are protected by ancient mechanisms designed to eliminate intruders. Some platforms trigger metal spikes when they detect weight, while others react to proximity, raising spikes from a red core charged with arcane energy. They are fast, lethal, and unpredictable traps, created to keep out anyone daring to challenge the clan's dominion. If you'd like, I can make a shorter version for a card, or a more epic one for ambiance.",
    "MISSIONS PRINCIPALS": "MAIN MISSIONS",
    "\"La teva supervivència depèn de la teva capacitat per adaptar-te i superar els reptes de l'abisme.\"": "\"Your survival depends on your ability to adapt and overcome the challenges of the abyss.\"",
    "01": "01",
    "Escapa de les trampes!": "Escape the traps!",
    "L'entorn és el teu primer enemic. Hi ha diversos puzzles i trampes repartides arreu de la masmorra. Sigues cautelós, observa els patrons i utilitza la teva agudesa mental per no caure-hi.": "The environment is your first enemy. There are various puzzles and traps scattered throughout the dungeon. Be cautious, observe patterns, and use your mental sharpness to avoid falling into them.",
    "02": "02",
    "Que no t'enganin!": "Don't let them fool you!",
    "Trobaràs enemics que intentaran aturar-te a qualsevol preu. Però compte: no tot el que es mou a la foscor és hostil. Alguns éssers poden ser vitals per a la teva experiència si saps com interactuar-hi.": "You'll find enemies who will try to stop you at all costs. But beware: not everything moving in the dark is hostile. Some beings can be vital to your experience if you know how to interact with them.",
    "03": "03",
    "Escapa amb vida": "Escape alive",
    "L'objectiu final és la llibertat. Però a quin preu? La teva integritat física i mental es veurà posada a prova en cada nivell. Només aquells que sàpiguen gestionar els seus recursos arribaran a la sortida.": "The ultimate goal is freedom. But at what cost? Your physical and mental integrity will be put to the test in each level. Only those who know how to manage their resources will reach the exit.",
    "04": "04",
    "Troba informació": "Find information",
    "Descobreix el perquè del teu segrest. El món de OUT amaga secrets antics sobre el conflicte entre orcs i draconians. Troba documents i relats que revelin els plans ocults dels teus captors.": "Discover the reason for your kidnapping. The world of OUT hides ancient secrets about the conflict between orcs and draconians. Find documents and stories that reveal the hidden plans of your captors.",
    "Encara no hi ha dades al rànquing.": "There's no data in the ranking yet.",
    "Saló de la Fama": "Hall of Fame",
    "Primer lloc": "First place",
    "Segon lloc": "Second place",
    "Tercer lloc": "Third place",
    "Resta de jugadors": "Other players",
    "Nom": "Name",
    "Escriu el teu nom...": "Write your name...",
    "Gmail": "Email",
    "escriu.el.teu@gmail.com": "write.your.email@gmail.com",
    "Comentari": "Comment",
    "Escriu el teu comentari...": "Write your comment...",
    "Enviar comentari": "Send comment",
    "Comentaris enviats": "Sent comments",
    "Encara no hi ha comentaris.": "No comments yet."
  }
};
